server:
  port: 8080

spring:
  application:
    name: backend-forum-system
  datasource:
    url: jdbc:mysql://localhost:3306/forum?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: forum
    password: forum
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://localhost:9200
  cache:
    type: redis

forum:
  hot-post-limit: 20
